name = "sankt-sven"
author = "Adam Kit and Gijs Derks"
description = "Simple Pedestal Model"


[dependencies]
odepack.git = "https://github.com/Nicholaswogan/odepack"

[fortran]
source-form = "default"
implicit-external = true
implicit-typing = true

[library]
source-dir = "src"

[build]
auto-executables = true